"""empty message

Revision ID: c5cc37d0c5a7
Revises: 953a3da0ec2f
Create Date: 2026-09-22 16:10:02.406052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cc37d0c5a7'
down_revision = '953a3da0ec2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_logo', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.BLOB(), nullable=True))
        batch_op.drop_column('hospital_logo')

    # ### end Alembic commands ###
